language: haxe

env:
  global:
    - GH_REF: github.com/deathbeam/parsihax.git

haxe:
  - development

before_install:
  - sudo apt-get update
  - sudo apt-get install mono-devel

hxml:
  - build.hxml
  - test.hxml

script:
  - haxe test.hxml
  - haxelib git dox https://github.com/HaxeFoundation/dox
  - rm -rf bin
  - mkdir bin
  - haxe doc.hxml

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: bin/api
  on:
    branch: master
